herois1 = dict()
hlist = list()

# HEROIS E CLASSES
herois = ['miya', ['a'],
          'bruno', ['a'],
          'clint', ['a'],
          'layla', ['a'],
          'roger', ['a', 's', 'ass'],
          'irithel', ['a'],
          'granger', ['a'],
          'wanwan', ['a'],
          'hanabi', ['a'],
          'yi sun-shin', ['a', 'ass'],
          'moskov', ['a'],
          'karrie', ['a'],
          'lesley', ['a'],
          'claude', ['a'],
          'kimmy', ['a'],
          'popol e kupa', ['a'],
          'brody', ['a'],
          'beatrix', ['a'],
          'natan', ['a'],
          'tigreal', ['t'],
          'franco', ['t'],
          'johnson', ['t'],
          'uranus', ['t'],
          'atlas', ['t'],
          'lolita', ['t', 'su'],
          'akai', ['t'],
          'grock', ['t'],
          'minotauro', ['t', 'su'],
          'hilda', ['t', 's'],
          'gatotkaca', ['t', 's'],
          'hylos', ['t'],
          'belerick', ['t'],
          'khufra', ['t'],
          'baxia', ['t'],
          'barats', ['t', 's'],
          'gloo', ['t'],
          'nana', ['m', 'su'],
          'eudora', ['m'],
          'gord', ['m'],
          'kagura', ['m'],
          'harley', ['m', 'ass'],
          'odette', ['m'],
          'zhask', ['m'],
          'change', ['m'],
          'selena', ['m', 'su'],
          'faramis', ['m', 'su'],
          'cecilion', ['m'],
          'luo yi', ['m'],
          'harith', ['m'],
          'cyclops', ['m'],
          'aurora', ['m'],
          'vexana', ['m'],
          'pharsa', ['m'],
          'valir', ['m'],
          'vale', ['m'],
          'lunox', ['m'],
          'kadita', ['m'],
          'esmeralda', ['m', 's'],
          'lylia', ['m'],
          'yve', ['m'],
          'alice', ['m', 's'],
          'balmond', ['s'],
          'alucard', ['s', 'ass'],
          'zilong', ['s', 'ass'],
          'chou', ['s'],
          'argus', ['s'],
          'x.borg', ['s'],
          'silvanna', ['s'],
          'yu zhong', ['s'],
          'badang', ['s'],
          'bane', ['s'],
          'freya', ['s', 'ass'],
          'sun', ['s'],
          'alpha', ['s'],
          'ruby', ['s'],
          'lapu-lapu', ['s'],
          'jawhead', ['s', 't', 'ass'],
          'martis', ['s'],
          'kaja', ['s', 'su'],
          'aldous', ['s'],
          'leomord', ['s'],
          'thamuz', ['s'],
          'minsitthar', ['s'],
          'terizla', ['s'],
          'dyrroth', ['s'],
          'masha', ['s'],
          'khaleed', ['s'],
          'paquito', ['s'],
          'phoveus', ['s'],
          'guinevere', ['s'],
          'angela', ['su'],
          'rafaela', ['su'],
          'estes', ['su'],
          'mathilda', ['m', 'su'],
          'diggie', ['su'],
          'carmilla', ['su'],
          'lancelot', ['ass'],
          'saber', ['ass'],
          'hayabusa', ['ass'],
          'helcurt', ['ass'],
          'gusion', ['ass'],
          'hanzo', ['ass'],
          'ling', ['ass'],
          'karina', ['ass'],
          'fanny', ['ass'],
          'benedetta', ['s', 'ass'],
          'natalia', ['s', 'ass'],
          'aulus', ['s'],
          'yin', ['s'],
          'aamon', ['ass'],
          'valentina', ['m'],
          'edith', ['s'],
          'floryn', ['sup']]

# COUNTERS
counters = ['alice', ['aurora', 'atlas', 'jawhead', 'argus', 'harley'],
            'guinevere', ['balmond', 'ruby', 'sun', 'badang', 'diggie'],
            'estes', ['saber', 'luo yi'],
            'carmilla', ['harith', 'masha', 'wanwan'],
            'masha', ['aldous'],
            'popol e kupa', ['hanzo', 'helcurt', 'gusion'],
            'esmeralda', ['baxia'],
            'benedetta', ['harith', 'kaja', 'wanwan'],
            'harith', ['phoveus'],
            'gusion', ['chou'],
            'brody', ['gusion'],
            'vale', ['kagura', 'kadita'],
            'karina', ['x.borg', 'kaja', 'khaleed', 'chou', 'lunox'],
            'akai', ['diggie', 'moskov', 'kagura', 'karrie', 'eudora'],
            'kagura', ['esmeralda'],
            'hanzo', ['natalia', 'benedetta', 'aamon', 'ling', 'valentina'],
            'saber', ['eudora', 'benedetta', 'diggie', 'faramis', 'minsitthar'],
            'fanny', ['akai', 'franco', 'eudora', 'lesley'],
            'harley', ['eudora', 'lancelot', 'ling', 'nana', 'lunox'],
            'gord', ['irithel', 'kimmy'],
            'valir', ['irithel', 'kimmy'],
            'silvanna', ['esmeralda'],
            'kimmy', ['lancelot'],
            'natalia', ['hylos', 'kaja', 'alice', 'thamuz', 'aldous'],
            'argus', ['valentina'],
            'wanwan', ['natalia', 'zilong', 'phoveus'],
            'sun', ['odette'],
            'claude', ['lesley'],
            'yu zhong', ['valentina'],
            'nana', ['natalia', 'helcurt', 'kaja', 'hayabusa', 'lesley'],
            'zilong', ['valentina', 'yu zhong'],
            'ruby', ['aurora', 'barats', 'kagura', 'kaja', 'baxia'],
            'tigreal', ['nana', 'wanwan', 'miya', 'harley', 'kagura'],
            'lunox', ['eudora'],
            'balmond', ['dyrroth', 'uranus', 'change', 'leomord', 'cyclops'],
            'miya', ['saber', 'kaja', 'karina', 'chou', 'helcurt'],
            'alucard', ['fanny', 'zhask', 'eudora', 'selena', 'khufra'],
            'franco', ['kagura', 'alpha', 'ruby', 'wanwan', 'chou'],
            'bane', ['alucard', 'bruno', 'zilong', 'chou', 'alpha'],
            'bruno', ['karina'],
            'johnson', ['esmeralda'],
            'zhask', ['valentina'],
            'angela', ['esmeralda'],
            'valentina', ['kagura', 'miya', 'wanwan', 'harith'],
            'edith', ['valentina'],
            'yin', ['valentina', 'khaleed'],
            'hanabi', ['benedetta', 'vale'],
            'yi sun-shin', ['zilong'],
            'karrie', ['benedetta'],
            'pharsa', ['zilong'],
            'jawhead', ['guinevere', 'diggie', 'lancelot', 'lunox', 'sun'],
            'leomord', ['valentina'],
            'barats', ['selena'],
            'beatrix', ['clint', 'mathilda', 'benedetta', 'natalia', 'chou'],
            'aulus', ['hayabusa', 'hanabi', 'popol e kupa']]

# FAVORAVEIS
favoraveis = ['odette', ['johnson'],
              'guinevere', ['minotauro', 'tigreal'],
              'tigreal', ['guinevere', 'wanwan', 'luo yi', 'alice'],
              'johnson', ['odette'],
              'minotauro', ['guinevere', 'alice'],
              'cecilion', ['carmilla'],
              'carmilla', ['cecilion'],
              'angela', ['zilong', 'ling', 'leomord', 'alpha'],
              'zilong', ['angela'],
              'karina', ['diggie'],
              'diggie', ['karina'],
              'wanwan', ['tigreal', 'belerick'],
              'belerick', ['wanwan'],
              'luo yi', ['tigreal', 'lolita'],
              'lolita', ['luo yi'],
              'ling', ['angela'],
              'alice', ['atlas', 'tigreal', 'minotauro'],
              'atlas', ['alice'],
              'harley', ['lesley'],
              'lesley', ['harley'],
              'leomord', ['angela'],
              'alpha', ['angela']]

# GERAR A LISTA
for c in range(0, len(herois), 2):
    herois1['heroi'] = herois[c]
    herois1['pontos_positivos'] = 0
    herois1['pontos_negativos'] = 0
    herois1['classe'] = list()
    for d in range(len(herois[c + 1])):
        herois1['classe'].append(herois[c + 1][d])
    herois1['counter'] = list()
    herois1['favoraveis'] = list()
    herois1['situacao'] = 'disponivel'

    if herois[c] in counters:
        pos = counters.index(herois[c])
        for d in range(len(counters[pos + 1])):
            herois1['counter'].append(counters[pos + 1][d])
    if herois[c] in favoraveis:
        pos = favoraveis.index(herois[c])
        for d in range(len(favoraveis[pos + 1])):
            herois1['favoraveis'].append(favoraveis[pos + 1][d])

    hlist.append(herois1.copy())
    herois1.clear()
print(hlist)
